#!/bin/bash
#SBATCH --partition=gpunodes
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --gres=gpu:1
#SBATCH --time=60
#SBATCH --job-name=job
#SBATCH --output=/w/340/lucbr/outs/slurm-%j.out


srun python3 src/cs-cluster/test-sbatch.py
